name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏 Please follow the sections in the template and provide as much information as possible about your problem.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is and what you were expecting.
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the extension are you running? This should appear in the dropdown on the top right of the popup.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Microsoft Edge
        - Safari
        - Other (Please specify)
    validations:
      required: true
  - type: input
    id: browser-name
    attributes:
      label: Other browser
      description: If you selected "other", please specify the browser here.
  - type: input
    id: browser-version
    attributes:
      label: Browser version number
      description: If you are not using the latest version of the browser (e.g. running on an older Chromebook), please specify the browser version number here.
