blank_issues_enabled: true
contact_links:
  - name: Discuss on Discord
    url: https://discord.gg/5Jp9drge9m
    about: Chat directly with other community members
  - name: Discuss on Reddit
    url: https://www.reddit.com/r/xcloudkeyboardmouse/
    about: Ask questions and discuss with other community members
