blank_issues_enabled: false
contact_links:
  - name: For support, please contact us via email: support@modernkit.one
    url: support@modernkit.one
    about: For the fastest support about bugs, payments, or feedback, please contact us via email.
  - name: Community support: Discuss on Discord
    url: https://discord.gg/5Jp9drge9m
    about: Chat directly with other community members. This will be slower and we may not see your issue.
  - name: Community support: Discuss on Reddit
    url: https://www.reddit.com/r/xcloudkeyboardmouse/
    about: Ask questions and discuss with other community members. This will be slower and we may not see your issue.
